#!/usr/bin/env python3
"""Generate machine-readable indexes and concatenated documentation for docs/."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"

GROUPS = {
    "en": [
        ("Start Here", ["quick-start-tutorial", "getting-started", "features-overview", "use-cases", "faq"]),
        ("Core References", ["cli-reference", "configuration", "security", "tools", "sessions", "skills", "workflow"]),
        ("Integrations and APIs", ["serve", "a2a", "acp", "sdk", "provider-guide", "skillhub"]),
        ("Architecture and Development", ["architecture", "development", "scenarios", "changelog"]),
    ],
    "zh": [
        ("入门", ["quick-start-tutorial", "getting-started", "features-overview", "use-cases", "faq"]),
        ("核心参考", ["cli-reference", "configuration", "security", "tools", "sessions", "skills", "workflow"]),
        ("集成与 API", ["serve", "a2a", "acp", "sdk", "provider-guide", "skillhub"]),
        ("架构与开发", ["architecture", "development", "scenarios", "changelog"]),
    ],
}


def title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def write_full(language: str, output: Path) -> None:
    files = sorted((DOCS / language).glob("*.md"))
    sections = [
        f"# MothX {'Documentation' if language == 'en' else '中文文档'} (Full)",
        "",
        "> This file is generated by `docs/scripts/generate-llms.py`. Do not edit it manually." if language == "en" else "> 此文件由 `docs/scripts/generate-llms.py` 自动生成，请勿手工编辑。",
        "",
    ]
    for path in files:
        relative = path.relative_to(ROOT).as_posix()
        sections.extend([f"## {title(path)}", "", f"Source: https://mothx.net/{language}/{path.name}", "", path.read_text(encoding="utf-8").strip(), "", "---", ""])
    output.write_text("\n".join(sections), encoding="utf-8")


def main() -> None:
    for language, groups in GROUPS.items():
        lines = [
            f"# MothX {'Documentation' if language == 'en' else '文档'}",
            "",
            "> Generated index. See the documentation home for the complete navigation." if language == "en" else "> 自动生成的文档索引。完整导航请查看文档首页。",
            "",
        ]
        for group, names in groups:
            lines.extend([f"## {group}", ""])
            for name in names:
                path = DOCS / language / f"{name}.md"
                if not path.is_file():
                    raise SystemExit(f"missing documentation file: {path}")
                lines.append(f"- [{title(path)}](https://mothx.net/{language}/{path.name})")
            lines.append("")
        lines.extend(["## Complete Content", "", f"- [Full {'English' if language == 'en' else 'Chinese'} Documentation](https://mothx.net/llms-full{'-zh' if language == 'zh' else ''}.txt)", ""])
        (DOCS / ("llms.txt" if language == "en" else "llms-zh.txt")).write_text("\n".join(lines), encoding="utf-8")
        write_full(language, DOCS / ("llms-full.txt" if language == "en" else "llms-full-zh.txt"))


if __name__ == "__main__":
    main()
